version: 2
sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_sales
        tests:
          - unique:
              column_name : (orders_id || "-" || pdt_id)
        columns:
          - name: date_date
          - name: orders_id
            tests:
              - not_null
          - name: pdt_id
          - name: quantity
          - name: revenue
      - name: raw_gz_product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - not_null
              - unique
          - name: purchse_price
      - name: raw_gz_ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
              - not_null
              - unique
          - name: shipping_fee
          - name: logcost
          - name: ship_cost

